#.travis.yml

language: node_js
node_js:
  - "8.2.1"

cache:
  directories:
    - ./portal-es/node_modules

env:
  global:
    - GITHUB_ORG="https://GH_TOKEN@github.com/pedlop"
    - GITHUB_NAME="Pedro Victor"
    - GITHUB_EMAIL="pedro_victor@hotmail.com"
    - NAME="integracao2017"

branches:
  only:
    - master

before_script:
  - cd portal-es
  - npm install

script:
  - npm run build
  - npm run auto:deploy

notifications:
  email: false